### ISSUE TITLE
`S3Storage.exists()` returns wrong result when `AWS_PRELOAD_METADATA` is True

### ISSUE THREAD

**Issue by malthejorgensen** [coagulant/django-storages-py3#7]
`S3Storage.exists()` returns `True` after having succesfully used `S3Storage.delete()` to delete the file when `AWS_PRELOAD_METADATA` is `True`

Example:

``` python
# settings.py
AWS_PRELOAD_METADATA = True

# example.py
store = S3Storage() # myfile.txt exists in the bucket
store.delete('myfile.txt')
store.exists('myfile.txt') # returns True
```

This is exactly what happens when you run `python manage.py collectstatic` when using `S3Storage()` as the staticfiles backend.

See: https://github.com/django/django/blob/1.7/django/contrib/staticfiles/management/commands/collectstatic.py#L305-315

**Comment by jbonfante** [comment]
Thanks
