### ISSUE TITLE
Placement of S3.py in package

### ISSUE THREAD

**Issue by malthejorgensen** [coagulant/django-storages-py3#9]
Right now the `S3.py` helper file is placed in the root of the repository.

The file `/storages/backends/s3.py` however expects it be to in the same directory as itself i.e. `/storages/backends`.
_See [this line](https://github.com/coagulant/django-storages-py3/blob/e6e68d8f66b0f6535e67a0761ad77bc9a3801225/storages/backends/s3.py#L13) in /storages/backends/s3.py._

That obviously won't work on case-insensitive filesystems, such as the default on Windows and some versions of OS X. (because `s3.py` and `S3.py` can't exist in the same directory)

Furthermore in order to set certain settings, you need to import  `S3.py` in your own code, e.g.

``` python
from S3 import CallingFormat
AWS_CALLING_FORMAT = CallingFormat.SUBDOMAIN
```

For these reason I propose we put `S3.py` in `/storages/utils`, so that it can be imported from the `django-storages-py3` package by user projects, and no moving around of files is needed in order to use the package:

``` python
from storages.utils.S3 import CallingFormat
AWS_CALLING_FORMAT = CallingFormat.SUBDOMAIN
```

**Comment by jbonfante** [comment]
Merged
